title      %BOOT_TITLE%
sort-key   %SORT_KEY%
linux      /vmlinux-%PKGBASE%
initrd     /initramfs-%PKGBASE%.img
devicetree /dtbs/%PKGBASE%/x1e78100-lenovo-thinkpad-t14s-oled-el2.dtb
options    %KERNEL_OPTIONS%
